//tealium universal tag - utag.11 ut4.0.201612082118, Copyright 2016 Tealium.com Inc. All Rights Reserved.
if(typeof window.mixpanel=='undefined'){(function(c,a){window.mixpanel=a;var b,d,h,e;b=c.createElement("script");b.type="text/javascript";b.async=!0;b.src=("https:"===c.location.protocol?"https:":"http:")+
'//cdn.mxpnl.com/libs/mixpanel-2.2.min.js';d=c.getElementsByTagName("script")[0];d.parentNode.insertBefore(b,d);a._i=[];a.init=function(b,c,f){function d(a,b){var c=b.split(".");2==c.length&&(a=a[c[0]],b=c[1]);a[b]=function(){a.push([b].concat(Array.prototype.slice.call(arguments,0)))}}var g=a;"undefined"!==typeof f?g=a[f]=[]:f="mixpanel";g.people=g.people||[];h=['disable','track','track_pageview','track_links','track_forms','register','register_once','unregister','identify','alias','name_tag','set_config','people.set','people.set_once','people.increment','people.track_charge','people.append'];for(e=0;e<h.length;e++)d(g,h[e]);a._i.push([b,c,f])};a.__SV=1.2;})(document,window.mixpanel||[]);mixpanel.init("e39a4ba8174726fb79f6a6c77b7a5247");}
try{(function(id,loader,u){try{u=utag.o[loader].sender[id]={}}catch(e){u=utag.sender[id]};u.ev={'view':1,'link':1};u.event_name="";u.people={};u.properties={};u.event_list={"event_name":1,"track_event_name":1,"loaded":1,"identify":1,"alias":1,"register":1};u.map={"mp_event":"track_event_name","js_page.MP_REGISTER_DATA":"register","eventData":"properties","mp_properties":"properties","mp_concat2":"track_event_name","invite_code":"invite_code","referrals_landing_mobile":"referrals_landing_mobile"};u.extend=[function(a,b){try{if(b['eventName'].toString().toLowerCase().indexOf('u4b'.toLowerCase())>-1){b['mp_event']=b['eventName']}}catch(e){utag.DB(e)}},function(a,b,c,d){try{if((typeof b['eventName2']!='undefined'&&typeof b['eventType2']!='undefined')){c=[b['eventName2'],b['eventType2']];b['mp_concat2']=c.join('.')}}catch(e){utag.DB(e)}},function(a,b){try{if((b['dom.url'].toString().indexOf('uber.com/business')>-1&&b['dom.viewport_height'].toString().indexOf('business.uber.com')>-1)){b['mp_event']=b['eventName']}}catch(e){utag.DB(e)}},function(a,b,c,d){try{if((typeof b['eventName']!='undefined'&&typeof b['eventType']!='undefined')||(b['from_signup']!='1'&&b['dom.url'].toString().indexOf('/dashboard/vehicle')<0&&typeof b['eventName']!='undefined'&&typeof b['eventType']!='undefined')){c=[b['eventName'],b['eventType']];b['mp_event']=c.join('.')}}catch(e){utag.DB(e)}},function(a,b){try{if(b['eventName2']=='web.drivers.signup.success'){b['mp_concat2']=b['eventName2']}}catch(e){utag.DB(e)}},function(a,b){function getQueryParam(url,param){param=param.replace(/[\[]/,"\\\[").replace(/[\]]/,"\\\]");var regexS="[\\?&]"+param+"=([^&#]*)",regex=new RegExp(regexS),results=regex.exec(url);if(results===null||(results&&typeof(results[1])!=='string'&&results[1].length)){return'';}else{return decodeURIComponent(results[1]).replace(/\+/g,' ');}};function campaignParams(){var campaign_keywords='utm_source utm_medium utm_campaign utm_content utm_term'.split(' '),kw='',params={},first_params={};var index;for(index=0;index<campaign_keywords.length;++index){kw=getQueryParam(document.URL,campaign_keywords[index]);if(kw.length){params[campaign_keywords[index]+' [last touch]']=kw;}}
for(index=0;index<campaign_keywords.length;++index){kw=getQueryParam(document.URL,campaign_keywords[index]);if(kw.length){first_params[campaign_keywords[index]+' [first touch]']=kw;}}
mixpanel.register(params);mixpanel.register_once(first_params);mixpanel.people.set_once(first_params);}
campaignParams();mixpanel.register_once({"Lead Page":document.URL});},function(a,b){if(document.location.href=='https://www.uber.com/'&&typeof window.mixpanel!='undefined'&&mixpanel.disable){mixpanel.disable()}},function(a,b){if(typeof window.mixpanel!='undefined'&&window.utag_data['invite_code']==true){mixpanel.register('invite_code','true');}
if(typeof window.mixpanel!='undefined'&&window.utag_data['cp.ag_fid']!='undefined'){mixpanel.register('ag_fid',window.utag_data["cp.ag_fid"]);}},function(a,b){try{if(typeof b['event_type']!='undefined'&&b['event_type']!=''){b['mp_event']=b['event_type']}}catch(e){utag.DB(e)}}];u.send=function(a,b,c,d,e,f){if(u.ev[a]||typeof u.ev.all!="undefined"){u.people.set={};u.people.set_once={};u.people.increment={};for(c=0;c<u.extend.length;c++){try{d=u.extend[c](a,b);if(d==false)return}catch(e){}};c={};for(d in utag.loader.GV(u.map)){if(typeof b[d]!=="undefined"&&b[d]!==""){e=u.map[d].split(",");for(f=0;f<e.length;f++){if(u.event_list[e[f]]){u[e[f]]=b[d];}else if(e[f]=="properties"){u.properties=b[d];}else if(e[f].indexOf("people.")==0){var g=7+e[f].substring(7).indexOf(".");u.people[e[f].substring(7,g)][e[f].substring(g+1)]=b[d];u.people[e[f].substring(7,g)+"_flag"]=1;}else{c[e[f]]=b[d]}}}}
if(u.track_event_name){u.event_name=u.track_event_name;}
if(Object.keys(u.properties).length!==0){c=u.properties;}
if(u.loaded){mixpanel.set_config({loaded:u.loaded});}
if(u.people.set_flag){mixpanel.people.set(u.people.set);}
if(u.people.set_once_flag){mixpanel.people.set_once(u.people.set_once);}
if(u.people.increment_flag){mixpanel.people.increment(u.people.increment);}
if(u.alias){mixpanel.alias(u.alias);}
if(u.identify){mixpanel.identify(u.identify);}
if(u.register){mixpanel.register(u.register);}
if(u.event_name){mixpanel.track(u.event_name,c);}}}
try{utag.o[loader].loader.LOAD(id)}catch(e){utag.loader.LOAD(id)}})('11','uber.main');}catch(e){}
